### ISSUE TITLE
Broken link on nearest neighbors on part2.ipynb

### ISSUE THREAD

**Issue by surak** [deeplearning540/lesson02#1]
The right link is to https://sebastianraschka.com/resources/ml-lectures-1/#l02-nearest-neighbor-methods

you pointed to https://sebastianraschka.com/resources/ml-lectures-1.html#l02-nearest-neighbor-methods , which is 404

**Comment by psteinb** [comment]
Thank you! This is much appreciated.
Fixed with https://github.com/deeplearning540/lesson02/commit/55ccaf500c8fcbd80159b80bc70c2bcada59be75
